name: Sytral RT Auto Update

on:
  schedule:
    - cron: '*/5 * * * *' # S'exécute toutes les 5 minutes
  workflow_dispatch:      # Permet de le lancer manuellement depuis l'onglet "Actions"

jobs:
  update:
    runs-on: ubuntu-latest
    # Important : donne le droit d'écrire les fichiers JSON sur ton dépôt
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests
      - name: Run Update Script
        env:
          GRANDLYON_USER: ${{ secrets.GRANDLYON_USER }}
          GRANDLYON_PASS: ${{ secrets.GRANDLYON_PASS }}
        run: python api/index.py  # Vérifie bien que ce nom est écrit !

      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # On ajoute tout le dossier data au cas où
          git add data/*.json 
          git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
          git push
